#!/usr/bin/env bash
##
# cibuild - CI script for the num_cpus project - A cross-platform shell script to determine the number of logical processors currently online and available
#
# Written in 2026 by Stephen G. Tuggy <sgt@stephengtuggy.com>
#
# To the extent possible under law, the author(s) have dedicated all copyright and related and neighboring rights to this
# software to the public domain worldwide. This software is distributed without any warranty.
#
# You should have received a copy of the CC0 Public Domain Dedication along with this software. If not, see
# <http://creativecommons.org/publicdomain/zero/1.0/>.
#

set -e

DOCKER_IMAGE_NAME="local-image:$(echo "$FROM" | sed 's/:/_/' | sed 's/\//_/')"
DOCKER_CONTAINER_NAME="local-container_$(echo "$FROM" | sed 's/:/_/' | sed 's/\//_/')"
docker build --build-arg from="$FROM" -t "$DOCKER_IMAGE_NAME" .
docker run --rm --name "$DOCKER_CONTAINER_NAME" "$DOCKER_IMAGE_NAME"

echo "cibuild Done!"
