##
# linux-inside-docker.yml - A GitHub Actions workflow to test num_cpus.sh
#
# Written in 2026 by Stephen G. Tuggy <sgt@stephengtuggy.com>
#
# To the extent possible under law, the author(s) have dedicated all copyright and related and neighboring rights to this
# software to the public domain worldwide. This software is distributed without any warranty.
#
# You should have received a copy of the CC0 Public Domain Dedication along with this software. If not, see
# <http://creativecommons.org/publicdomain/zero/1.0/>.
#

name: linux-inside-docker.yml
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  run_shell_script:
    name: Run Shell Script inside Docker
    runs-on: ubuntu-24.04
    continue-on-error: ${{ matrix.allow_failure }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - FROM:           'ubuntu:questing'
            allow_failure:  false
          - FROM:           'ubuntu:noble'
            allow_failure:  false
          - FROM:           'linuxmintd/mint22.2-amd64'
            allow_failure:  false
          - FROM:           'linuxmintd/mint22-amd64'
            allow_failure:  false
          - FROM:           'dhi.io/python:3.14-debian13-dev'
            allow_failure:  false
          - FROM:           'debian:bookworm'
            allow_failure:  false
          - FROM:           'fedora:43'
            allow_failure:  false
          - FROM:           'fedora:42'
            allow_failure:  false
          - FROM:           'fedora:41'
            allow_failure:  false
          - FROM:           'opensuse/leap:16.0'
            allow_failure:  false
          - FROM:           'opensuse/leap:15.6'
            allow_failure:  false
          - FROM:           'rockylinux/rockylinux:10.1'
            allow_failure:  false
          - FROM:           'rockylinux/rockylinux:10.0'
            allow_failure:  false
          - FROM:           'rockylinux/rockylinux:9.7'
            allow_failure:  false
          - FROM:           'archlinux:latest'
            allow_failure:  false
          - FROM:           'manjarolinux/base'
            allow_failure:  true

    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          fetch-depth: 2
          submodules: false

      - name: Run CI
        env:
          FROM:       ${{ matrix.FROM }}
        run: ./cibuild
        shell: bash
