name: shell-script.yml
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  run_shell_script:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-2022
            shell: cmd
          - os: windows-2022
            shell: pwsh
          - os: windows-2025
            shell: cmd
          - os: windows-2025
            shell: pwsh
          - os: macos-14
            shell: sh
          - os: macos-14
            shell: bash
          - os: macos-15
            shell: sh
          - os: macos-15
            shell: bash
          - os: macos-15-intel
            shell: sh
          - os: macos-15-intel
            shell: bash
          - os: ubuntu-22.04
            shell: sh
          - os: ubuntu-22.04
            shell: bash
          - os: ubuntu-24.04
            shell: sh
          - os: ubuntu-24.04
            shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Run Shell Script
        run: ./num_cpus
        shell: ${{ matrix.shell }}
