name: shell-script.yml
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  run_shell_script:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-2022
          - os: windows-2025
          - os: macos-14
          - os: macos-15
          - os: macos-15-intel
          - os: ubuntu-22.04
          - os: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Run Shell Script in Bash (Ubuntu)
        run: ./num_cpus
        shell: bash
        if: contains(matrix.os, 'ubuntu')

      - name: Run Shell Script in sh (Ubuntu)
        run: ./num_cpus
        shell: sh
        if: contains(matrix.os, 'ubuntu')

      - name: Run Shell Script in Bash (macOS)
        run: ./num_cpus
        shell: bash
        if: contains(matrix.os, 'macos')

      - name: Run Shell Script in sh (macOS)
        run: ./num_cpus
        shell: sh
        if: contains(matrix.os, 'macos')

      - name: Run Shell Script in cmd.exe (Windows)
        run: .\num_cpus
        shell: cmd
        if: contains(matrix.os, 'windows')

      - name: Run Shell Script in pwsh (Windows)
        run: .\num_cpus
        shell: pwsh
        if: contains(matrix.os, 'windows')

      - name: Run Shell Script in PowerShell (Windows)
        run: .\num_cpus
        shell: PowerShell
        if: contains(matrix.os, 'windows')
